# The file throws an error when running docker-compose up seems we cannot connect to the db, please consider add dependencies to the docker file:
# See doc:
# - https://docs.docker.com/compose/how-tos/startup-order/
# - 
version: "3.8" # version is deprecated please remove this

services:
  db:
    image: mysql:8.0
    restart: always
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql

  wordpress:
    image: wordpress:latest
    restart: always
    ports:
      - "8080:80"
    env_file: .env
    volumes:
      - wp-data:/var/www/html

volumes:
  db_data:
  wp-data:
